'use client';
import { useRef, useState } from 'react';
import Link from 'next/link';
import { roles } from '@/lib/content';
import { downloadText, saveCareer, removeCareer, useWorkspace, type CareerInterest } from '@/lib/storage';
import { Arrow, ArrowUpRight, Check, Close } from './icons';
const blank: CareerInterest = { role: '', name: '', email: '', note: '', savedAt: '' };
export function Careers() {
  const [active,setActive] = useState<string|null>(null); const [done,setDone] = useState(false); const [error,setError] = useState(''); const panel = useRef<HTMLDialogElement>(null); const state = useWorkspace();
  const role = roles.find(r => r.id === active); const profile = state.careers.find(c => c.role === active) ?? { ...blank, role: active ?? '' };
  function open(id: string) { setActive(id); setDone(false); setError(''); panel.current?.showModal(); }
  function update(key: keyof CareerInterest,value: string) { saveCareer({ ...profile,[key]:value,savedAt:new Date().toISOString() }, false); }
  function submit(e: React.FormEvent) { e.preventDefault(); if (profile.name.trim().length<2 || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(profile.email)) { setError('Enter your name and a valid email address.'); return; } saveCareer({ ...profile, savedAt: new Date().toISOString() }); setDone(true); setError(''); }
  return <><div className="roles-list">{roles.map(r => <article key={r.id}><div><h3>{r.title}</h3><p>{r.location} <span aria-hidden="true">/</span> {r.discipline} <span aria-hidden="true">/</span> {r.type}</p></div><button className="text-link" onClick={() => open(r.id)}>View opportunity <ArrowUpRight size={20}/></button></article>)}</div><dialog ref={panel} className="role-dialog" aria-labelledby="role-title" onClose={() => setActive(null)}><button className="role-close icon-button" aria-label="Close opportunity" onClick={() => panel.current?.close()}><Close/></button>{role && <div className="role-content"><span className="role-location">{role.location} · {role.type}</span><h2 id="role-title">{role.title}</h2><p className="role-intro">{role.intro}</p><div className="role-requirements"><h3>What you’ll do</h3><ul>{role.responsibilities.map(s => <li key={s}>{s}</li>)}</ul><h3>What you’ll bring</h3><ul>{role.requirements.map(s => <li key={s}>{s}</li>)}</ul></div>{done ? <div className="career-success"><Check size={32}/><h3>Your career profile is ready.</h3><p>Your details are saved in this browser. Download your profile whenever you need it.</p><div className="record-actions"><button className="button" onClick={() => downloadText(`northforge-${role.id}.txt`,`NORTHFORGE GROUP\nCAREER PROFILE\n\nRole: ${role.title}\nLocation: ${role.location}\nName: ${profile.name}\nEmail: ${profile.email}\n\n${profile.note}\n\nSaved: ${profile.savedAt}\n`)}>Download profile <Arrow size={17}/></button><button className="button button-outline" onClick={() => setDone(false)}>Edit details</button></div><button className="discard-draft" onClick={() => { if(window.confirm('Remove your profile for this opportunity?')) { removeCareer(role.id); setDone(false); } }}>Remove profile</button></div> : <form onSubmit={submit} noValidate className="career-form"><h3>Introduce yourself.</h3><p>Prepare a short profile for this opportunity.</p>{error && <p role="alert" className="field-error">{error}</p>}<div className="form-grid"><div className="field"><label htmlFor="career-name">Name *</label><input id="career-name" autoComplete="name" value={profile.name} onChange={e => update('name',e.target.value)} maxLength={160} required/></div><div className="field"><label htmlFor="career-email">Email *</label><input id="career-email" type="email" autoComplete="email" value={profile.email} onChange={e => update('email',e.target.value)} maxLength={254} required/></div><div className="field full"><label htmlFor="career-note">A little about you <span>(optional)</span></label><textarea id="career-note" rows={4} value={profile.note} onChange={e => update('note',e.target.value)} maxLength={3000}/></div></div><p className="data-note">Your profile stays in this browser. Download it to share. <Link href="/privacy/" onClick={() => panel.current?.close()}>Privacy & data</Link></p><button className="button" type="submit">Save career profile <Arrow size={17}/></button></form>}</div>}</dialog></>;
}
