import Link from 'next/link';
import { Arrow, ArrowUpRight } from './icons';
import { Brand } from './brand';
import { detailCropProjects, expertise, expertiseById, imagePath, type Project } from '@/lib/content';
import { SaveButton } from './workspace-ui';
export function Photo({ id, index = 1, alt, className = '', priority = false, sizes = '100vw' }: { id: string; index?: number; alt: string; className?: string; priority?: boolean; sizes?: string }) {
  return <img src={imagePath(id, index)} srcSet={`${imagePath(id, index, true)} 720w, ${imagePath(id, index)} 1920w`} sizes={sizes} width="1920" height="1080" className={`${className}${index === 2 && detailCropProjects.includes(id) ? ' photo-detail-crop' : ''}`} alt={alt} loading={priority ? 'eager' : 'lazy'} fetchPriority={priority ? 'high' : 'auto'} decoding="async" />;
}
export function ProjectCard({ project, wide = false, index }: { project: Project; wide?: boolean; index?: number }) {
  return <article className={`project-card ${wide ? 'wide' : ''}`}><div className="project-photo"><Link href={`/projects/${project.id}/`} aria-label={`Explore ${project.name}`}><Photo id={project.id} alt={project.captions[0]} sizes={wide ? '(min-width: 900px) 65vw, 100vw' : '(min-width: 700px) 50vw, 100vw'} /><span className="photo-arrow"><ArrowUpRight /></span></Link><SaveButton id={project.id} /></div><div className="project-card-meta"><span>{expertiseById(project.expertise).short}</span><span>{project.country}</span></div><Link className="project-title-link" href={`/projects/${project.id}/`}><h3>{project.name}</h3><ArrowUpRight /></Link>{index !== undefined && <span className="sr-only">Project {index + 1}</span>}</article>;
}
export function TextLink({ href, children, className = '' }: { href: string; children: React.ReactNode; className?: string }) { return <Link className={`text-link ${className}`} href={href}>{children}<ArrowUpRight size={19} /></Link>; }
export function ContactBand({ discipline, region, title = 'What are you building next?' }: { discipline?: string; region?: string; title?: string }) {
  const params = new URLSearchParams(); if (discipline) params.set('expertise', discipline); if (region) params.set('region', region);
  return <section className="contact-band wrap"><div><h2>{title}</h2></div><Link href={`/contact/${params.size ? `?${params}` : ''}`} className="round-link" aria-label="Discuss a project"><ArrowUpRight size={36} /></Link></section>;
}
export function Footer() { return <footer className="site-footer"><div className="wrap footer-main"><div className="footer-brand"><Link href="/" aria-label="NORTHFORGE GROUP home"><Brand large /></Link><p>Engineering what matters.<br /> Building what lasts.</p></div><nav aria-label="Company links"><p>The group</p><Link href="/group/">About NORTHFORGE</Link><Link href="/global/">Global presence</Link><Link href="/careers/">Careers</Link><Link href="/contact/">Contact</Link></nav><nav aria-label="Expertise links"><p>Our expertise</p>{expertise.map(e => <Link href={`/expertise/${e.id}/`} key={e.id}>{e.name}</Link>)}</nav><div className="footer-note"><span>Great work starts<br /> with a good question.</span><TextLink href="/contact/">Discuss a project</TextLink></div></div><div className="wrap footer-bottom"><span>© {new Date().getFullYear()} NORTHFORGE GROUP</span><div><Link href="/privacy/">Privacy</Link><Link href="/website-information/">Website information</Link><a href="#main" className="back-top">Back to top <Arrow style={{ transform: 'rotate(-90deg)' }} size={16} /></a></div></div></footer>; }
export function Breadcrumb({ items }: { items: { label: string; href?: string }[] }) { return <nav className="breadcrumb" aria-label="Breadcrumb"><Link href="/">Home</Link>{items.map((item, i) => <span key={i}><span aria-hidden="true">/</span>{item.href ? <Link href={item.href}>{item.label}</Link> : <span aria-current="page">{item.label}</span>}</span>)}</nav>; }
