export type ExpertiseId = 'transport' | 'marine' | 'industrial' | 'water-energy';
export type Expertise = { id: ExpertiseId; name: string; short: string; title: string; description: string; intro: string; scopes: string[]; approach: string[]; image: string; };
export const expertise: Expertise[] = [
  { id: 'transport', name: 'Transport infrastructure', short: 'Transport', title: 'Make the connection.', description: 'Bridges, railways and road networks that bring places closer.', intro: 'Every connection has a wider purpose. We bring structural, ground and construction expertise together to deliver the routes people and industry rely on.', scopes: ['Bridges and viaducts', 'Rail and freight corridors', 'Tunnels and underground works', 'Highways and interchanges', 'Foundations and earthworks', 'Asset renewal'], approach: ['Understand the corridor', 'Design around the constraints', 'Build with movement in mind'], image: 'north-channel-crossing' },
  { id: 'marine', name: 'Ports & marine works', short: 'Ports & marine', title: 'Where land meets possibility.', description: 'Working ports and resilient coastlines, built around the water.', intro: 'Water changes the conditions, every day. Our marine teams combine coastal engineering, heavy civil works and careful phasing to build infrastructure that keeps working through the tide.', scopes: ['Container terminals', 'Quay walls and berths', 'Breakwaters and sea defences', 'Marine foundations', 'Harbour access works', 'Coastal reinforcement'], approach: ['Read the marine environment', 'Protect working access', 'Coordinate land and water'], image: 'kestrel-container-terminal' },
  { id: 'industrial', name: 'Industrial facilities', short: 'Industrial', title: 'Give industry room to work.', description: 'Production, processing and logistics, connected from the ground up.', intro: 'A productive facility starts with how everything connects. We integrate buildings, structures, access and utilities into a clear plan for construction and long-term operation.', scopes: ['Manufacturing campuses', 'Processing facilities', 'Logistics buildings', 'Heavy equipment foundations', 'Utility corridors', 'Operational extensions'], approach: ['Map the operation', 'Resolve the interfaces', 'Sequence for commissioning'], image: 'redstone-industrial-campus' },
  { id: 'water-energy', name: 'Water & energy infrastructure', short: 'Water & energy', title: 'Build the essential.', description: 'The civil infrastructure behind reliable water and energy systems.', intro: 'Essential services depend on sound foundations. We deliver the structures, networks and site infrastructure that connect water and energy systems to the places they serve.', scopes: ['Water treatment facilities', 'Pumping infrastructure', 'Storage and distribution', 'Substation civil works', 'Cable and service routes', 'Access and drainage'], approach: ['Understand the whole system', 'Coordinate specialist equipment', 'Plan for everyday maintenance'], image: 'wadi-water-programme' },
];
export const regions = [
  { id: 'northern-europe', name: 'Northern Europe', team: 'Northern Europe project team' },
  { id: 'atlantic-europe', name: 'Atlantic Europe', team: 'Atlantic Europe project team' },
  { id: 'north-africa', name: 'North Africa', team: 'North Africa project team' },
  { id: 'southeast-asia', name: 'Southeast Asia', team: 'Asia Pacific project team' },
  { id: 'north-america', name: 'North America', team: 'North America project team' },
  { id: 'south-america', name: 'South America', team: 'South America project team' },
  { id: 'middle-east', name: 'Middle East', team: 'Middle East project team' },
  { id: 'oceania', name: 'Oceania', team: 'Asia Pacific project team' },
];
export type Project = {
  id: string; name: string; country: string; location: string; region: string;
  expertise: ExpertiseId; stage: string; year: string; coordinates: [number, number];
  headline: string; summary: string; challenge: string; response: string; perspective: string;
  scope: string[]; facts: [string, string][]; captions: string[]; flagship?: boolean;
};
export const projects: Project[] = [
  { id: 'north-channel-crossing', name: 'North Channel Crossing', country: 'Norway', location: 'Western Norway', region: 'northern-europe', expertise: 'transport', stage: 'In delivery', year: '2026', coordinates: [5.32, 60.39], flagship: true,
    headline: 'A new line across the water.', summary: 'A coastal connection shaped by the fjord, the shipping channel and the communities on either shore.',
    challenge: 'A bridge is more than the distance between two points. At North Channel, the crossing must bring coastal routes together while keeping a deep-water passage open below. Steep shorelines, exposed weather and variable ground conditions make the approach works as important as the main span. Construction access has to follow the terrain without overwhelming it.',
    response: 'The cable-stayed arrangement concentrates the major supports outside the navigation channel. Marine foundations, pylons and deck sections follow a coordinated sequence, with shoreline works progressing alongside the main structure. Dedicated access plans separate construction movements from the surrounding road network, while the approaches follow the existing contours as closely as practical.',
    perspective: 'From the bearing assemblies to the drainage routes, inspection and maintenance access are part of the design. The result is a crossing considered at every scale: a clear line in the landscape, supported by thousands of carefully resolved connections.',
    scope: ['Marine foundations', 'Cable-stayed structure', 'Deck and approach roads', 'Drainage and access'], facts: [['Structure', 'Cable-stayed crossing'], ['Setting', 'Coastal fjord'], ['Delivery', 'Integrated civil works']], captions: ['The crossing and its relationship to the fjord.', 'The main span keeps the navigation channel clear.', 'Cable, deck and pylon connections at close range.', 'Approach works follow the coastal terrain.'] },
  { id: 'atlas-freight-corridor', name: 'Atlas Freight Corridor', country: 'Morocco', location: 'Casablanca hinterland', region: 'north-africa', expertise: 'transport', stage: 'In delivery', year: '2026', coordinates: [-7.59, 33.57],
    headline: 'Keep the region moving.', summary: 'A freight corridor linking industrial districts with a dependable route to the coast.',
    challenge: 'The corridor crosses changing terrain and an established network of roads and services. Its success depends on the connections around the railway as much as the track itself. Earthworks, crossings and drainage need to form a continuous system while adjacent industrial districts remain accessible.',
    response: 'The programme brings ground preparation, rail formation and crossing structures into a phased delivery plan. Work fronts are organised around existing access points, with service diversions resolved before the main earthworks move through each section. Drainage is considered along the full corridor, including the transition between cuttings and embankments.',
    perspective: 'A consistent approach to interfaces makes each section ready for the work that follows. The completed civil formation provides a legible, maintainable route for rail systems installation and a stronger physical connection between production areas and the regional freight network.',
    scope: ['Rail formation', 'Earthworks and drainage', 'Road crossings', 'Utility diversions'], facts: [['Asset', 'Freight rail corridor'], ['Setting', 'Industrial hinterland'], ['Delivery', 'Phased civil programme']], captions: ['A continuous route through the industrial hinterland.', 'Rail formation and drainage are designed as one system.'] },
  { id: 'kestrel-container-terminal', name: 'Kestrel Container Terminal', country: 'Malaysia', location: 'Southern Malaysia', region: 'southeast-asia', expertise: 'marine', stage: 'In delivery', year: '2026', coordinates: [103.74, 1.49], flagship: true,
    headline: 'Built around the flow.', summary: 'Marine and landside infrastructure brought together for a new chapter in cargo movement.',
    challenge: 'A terminal works as a sequence: ship to quay, quay to stack, stack to road. Each interface at Kestrel needs to serve that movement while allowing the port to grow in stages. Heavy operational loads, marine exposure and the need for clear construction boundaries shape the civil engineering from the outset.',
    response: 'Quay structures, crane foundations and hardstanding are coordinated with the terminal layout. The delivery sequence establishes a complete working zone before extending into the next phase. Beneath the surface, drainage and service corridors anticipate the positions of future equipment, reducing the need to reopen areas prepared for operation.',
    perspective: 'Long-term use guides the details. Pavement transitions respond to different loading conditions, inspection access remains clear, and each phase connects to the next without an unresolved edge. It is an approach that treats the harbour and the land behind it as a single piece of infrastructure.',
    scope: ['Quay and marine foundations', 'Crane infrastructure', 'Container hardstanding', 'Landside connections'], facts: [['Asset', 'Container terminal'], ['Setting', 'Working harbour'], ['Delivery', 'Phased marine and civil works']], captions: ['Quay, container stacks and access routes work as a single system.', 'A clear transfer between the vessel and the landside operation.', 'Concrete details respond to heavy operational loads.', 'Crane infrastructure defines the working edge.'] },
  { id: 'westhaven-coastal-works', name: 'Westhaven Coastal Works', country: 'Portugal', location: 'Atlantic Portugal', region: 'atlantic-europe', expertise: 'marine', stage: 'Completed', year: '2025', coordinates: [-8.61, 41.15],
    headline: 'A considered edge to the Atlantic.', summary: 'Coastal protection and quay works shaped by tides, exposure and a working harbour.',
    challenge: 'At Westhaven, protecting the coastal edge cannot come at the expense of harbour access. Tidal changes and Atlantic weather affect when work can take place, while vessels and landside operations need a clear and predictable route through the site. Existing structures add another layer of interfaces to resolve.',
    response: 'The works combine a reinforced quay edge with carefully arranged coastal protection. Construction zones follow the harbour geometry, and the sequence is built around practical marine access windows. Material placement, temporary works and permanent structures are considered together so that one operation prepares the next.',
    perspective: 'The finished works establish a robust boundary between land and water. Inspection routes and access points remain part of the harbour, with details selected for an exposed setting and the realities of maintaining infrastructure at the shoreline.',
    scope: ['Quay reinforcement', 'Coastal protection', 'Marine access', 'Harbour drainage'], facts: [['Asset', 'Quay and breakwater'], ['Setting', 'Atlantic coastline'], ['Delivery', 'Marine construction']], captions: ['Protection and access meet at the working harbour.', 'The coastal edge responds to tides and wave exposure.'] },
  { id: 'redstone-industrial-campus', name: 'Redstone Industrial Campus', country: 'Canada', location: 'Southern Ontario', region: 'north-america', expertise: 'industrial', stage: 'Completed', year: '2025', coordinates: [-79.38, 43.65],
    headline: 'Space for industry to connect.', summary: 'A manufacturing campus that brings production, logistics and service infrastructure into one plan.',
    challenge: 'The campus must accommodate several kinds of movement at once: materials arriving, finished products leaving, people circulating and utilities reaching the production areas. Building envelopes alone cannot solve that brief. The groundworks and connections between buildings need the same attention as the structures themselves.',
    response: 'The layout establishes clear logistics routes and a coordinated service spine. Structural bays, equipment foundations and external works are developed together, allowing each building to connect to the broader campus. Construction is sequenced around defined handover areas, making the transition from civil works to equipment installation easier to plan.',
    perspective: 'Consistent details across the site make the whole campus easier to understand and maintain. The resulting infrastructure supports everyday operations while keeping the important access routes and utility interfaces clear for future changes to production.',
    scope: ['Structural steel buildings', 'Equipment foundations', 'Internal roads', 'Utility infrastructure'], facts: [['Asset', 'Manufacturing campus'], ['Setting', 'Industrial district'], ['Delivery', 'Structures and infrastructure']], captions: ['Production buildings and logistics routes share a coordinated plan.', 'Structural bays create clear, adaptable working space.'] },
  { id: 'mesa-processing-works', name: 'Mesa Processing Works', country: 'Chile', location: 'Northern Chile', region: 'south-america', expertise: 'industrial', stage: 'In delivery', year: '2026', coordinates: [-70.40, -23.65],
    headline: 'Work with the ground.', summary: 'An industrial processing facility organised around terrain, heavy loads and practical access.',
    challenge: 'The rocky landscape sets the conditions for Mesa. Changes in level influence the process arrangement, while heavy equipment and transport movements require reliable access. The civil works must support specialist systems without losing sight of the larger movement of people, materials and maintenance equipment around the site.',
    response: 'Terraced platforms establish clear working levels and connect through planned heavy-transport routes. Equipment foundations, retaining structures and service corridors are coordinated before construction reaches the process areas. The sequence brings access and drainage into use early, creating a stable basis for the more specialised structural and mechanical work.',
    perspective: 'The project brings large-scale site planning and precise equipment interfaces together. It gives each part of the operation a defined place, with maintenance access and inspection routes considered alongside the loads and geometry of the processing structures.',
    scope: ['Terraced platforms', 'Process foundations', 'Steel structures', 'Heavy transport routes'], facts: [['Asset', 'Processing facility'], ['Setting', 'Arid terrain'], ['Delivery', 'Industrial civil works']], captions: ['The facility follows a sequence of engineered working levels.', 'Process structures connect to planned service routes.'] },
  { id: 'wadi-water-programme', name: 'Wadi Water Programme', country: 'Oman', location: 'Northern Oman', region: 'middle-east', expertise: 'water-energy', stage: 'In delivery', year: '2026', coordinates: [58.41, 23.59], flagship: true,
    headline: 'Essential water. Enduring infrastructure.', summary: 'Treatment and pumping infrastructure designed as a connected system in a dry landscape.',
    challenge: 'Water infrastructure in a dry regional setting has to answer more than the process brief. The ground, heat, access and distance between facilities all influence how the system can be built and maintained. At Wadi, the civil works need to connect treatment structures with pumping and distribution infrastructure across an exposed site.',
    response: 'The programme brings basins, buildings and service routes into a coordinated layout. Construction sequencing protects the interfaces for specialist equipment and allows individual structures to be inspected before the next phase begins. External works establish drainage and maintenance access alongside the process infrastructure, rather than leaving them to the end.',
    perspective: 'An essential system must be understandable to the people who operate it. Clear access around structures, organised pipe routes and considered equipment spaces support day-to-day inspection. The civil design creates a practical setting for water treatment, from the first foundation to the final connection.',
    scope: ['Treatment structures', 'Pumping facilities', 'Pipeline support works', 'Site access and drainage'], facts: [['Asset', 'Water treatment and pumping'], ['Setting', 'Arid regional landscape'], ['Delivery', 'Connected civil programme']], captions: ['Treatment structures are arranged for a clear operating sequence.', 'Pumping infrastructure connects the stages of the water system.', 'Basins and access routes are considered together.', 'The site plan responds to the surrounding terrain.'] },
  { id: 'southern-grid-connection', name: 'Southern Grid Connection', country: 'Australia', location: 'South Australia', region: 'oceania', expertise: 'water-energy', stage: 'Completed', year: '2025', coordinates: [138.60, -34.93],
    headline: 'The foundations of connection.', summary: 'Substation civil works and access infrastructure supporting a regional power connection.',
    challenge: 'A power connection depends on precise interfaces between civil structures and electrical equipment. At Southern Grid, foundations, cable routes and access must work together across an open site. The sequence has to provide defined areas for equipment installation while construction continues safely around them.',
    response: 'The civil programme establishes the site platforms, drainage and access network before moving through equipment foundations and cable infrastructure. Setting-out, holding-down details and service entries are coordinated with the electrical layout. Defined handover zones give installation teams a clear, inspected area in which to work.',
    perspective: 'The infrastructure is arranged for long-term access as well as the installation programme. Equipment routes, inspection space and surface drainage form a coherent whole, supporting the regional connection through well-resolved civil engineering rather than unnecessary complexity.',
    scope: ['Equipment foundations', 'Cable trenches', 'Access infrastructure', 'Site drainage'], facts: [['Asset', 'Substation civil works'], ['Setting', 'Regional power network'], ['Delivery', 'Foundations and connections']], captions: ['The civil layout supports the complete electrical arrangement.', 'Foundations and cable routes are coordinated before installation.'] },
];
export const roles = [
  { id: 'senior-structural-engineer', title: 'Senior Structural Engineer', location: 'Northern Europe', discipline: 'Engineering', type: 'Full time', intro: 'Take structural ideas from a sound concept to a buildable detail, working closely with our transport and marine teams.', responsibilities: ['Develop and review structural designs for major civil works.', 'Coordinate ground, temporary works and construction interfaces.', 'Guide engineers through clear technical reviews and practical decisions.'], requirements: ['A civil or structural engineering qualification.', 'Experience delivering complex infrastructure designs.', 'Clear technical communication and a collaborative approach.'] },
  { id: 'marine-construction-manager', title: 'Marine Construction Manager', location: 'Southeast Asia', discipline: 'Construction', type: 'Full time', intro: 'Bring marine operations, site teams and permanent works together in a clear and achievable construction sequence.', responsibilities: ['Coordinate daily and look-ahead marine construction activities.', 'Plan around access, weather and operational constraints.', 'Lead site coordination with a consistent focus on safe delivery.'], requirements: ['Experience managing marine or heavy civil construction.', 'Sound knowledge of temporary works and site logistics.', 'The ability to lead multidisciplinary teams in the field.'] },
  { id: 'graduate-civil-engineer', title: 'Graduate Civil Engineer', location: 'Middle East', discipline: 'Early careers', type: 'Full time', intro: 'Build your engineering judgement through real design problems, site experience and support from experienced colleagues.', responsibilities: ['Support design, planning and construction coordination.', 'Prepare clear technical records and engineering calculations.', 'Learn through site observation and multidisciplinary reviews.'], requirements: ['A recent degree in civil engineering or a related subject.', 'An interest in water, energy or transport infrastructure.', 'Curiosity, care with detail and a willingness to learn.'] },
];
export const projectById = (id: string) => projects.find((p) => p.id === id);
export const expertiseById = (id: string) => expertise.find((e) => e.id === id)!;
export const regionById = (id: string) => regions.find((r) => r.id === id);
export const detailCropProjects = ['westhaven-coastal-works', 'mesa-processing-works', 'southern-grid-connection'];
export const imagePath = (id: string, index = 1, small = false) => `/images/${id}-${index === 2 && detailCropProjects.includes(id) ? 1 : index}${small ? '-small' : ''}.webp`;
